/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FerreteriaGUI;


import FerreteriaDAO.EmpleadosDAO;
import FerreteriaEntityClass.Cargos;
import FerreteriaEntityClass.Empleados;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN8
 */
public class EmpleadosGUI extends javax.swing.JFrame {
    
    private CargosGUI c = null;
        
    /**
     * Creates new form ClientesGUI
     */
    private EmpleadosDAO ejc = new EmpleadosDAO();
    private Empleados empleado = new Empleados();
    private String mensaje = "";
//    private EmpleadosDAO edao = new EmpleadosDAO();
    public EmpleadosGUI() {
        initComponents();
        
        this.setTitle("Formulario Empleados");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        llenarComboBoxCargos(ComboBoxCargos);
    
        
//        ManejadorEmpleado me = new ManejadorEmpleado();
//         BotonBuscar.addActionListener(me);
//         textoIdentificacion.addActionListener(me);
    }
    
    private void limpiarCampos() {
        textoIdentificacion.setText("");
        textoNombres.setText("");
        textoApellidos.setText("");
        groupEstadocivil.clearSelection();
        groupGenero.clearSelection();
        textoTelefono.setText("");
    }
    
    private void llenarComboBoxCargos(JComboBox ComboBoxCargos){
        ejc.getCargos(ComboBoxCargos);
    }

    private void inhabilitarEmpleado(String identificacion) {
        ejc.inhabilitarEmpleado(identificacion);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupEstadocivil = new javax.swing.ButtonGroup();
        groupGenero = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoTelefono = new javax.swing.JTextField();
        textoIdentificacion = new javax.swing.JTextField();
        textoNombres = new javax.swing.JTextField();
        textoApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BotonBuscar = new javax.swing.JButton();
        BotonRegistrar = new javax.swing.JButton();
        BotonActualizar = new javax.swing.JButton();
        BotonEliminar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        radioCasado = new javax.swing.JRadioButton();
        radioFemenino = new javax.swing.JRadioButton();
        radioSoltero = new javax.swing.JRadioButton();
        radioMasculino = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        radioMasculino1 = new javax.swing.JRadioButton();
        radioFemenino1 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        botonCargos = new javax.swing.JButton();
        ComboBoxCargos = new javax.swing.JComboBox<>();
        BotonUpdate = new javax.swing.JButton();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Teléfono:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Identificación:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Nombres:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cargo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        textoTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(textoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 220, -1));

        textoIdentificacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoIdentificacionActionPerformed(evt);
            }
        });
        textoIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoIdentificacionKeyTyped(evt);
            }
        });
        jPanel1.add(textoIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 130, -1));

        textoNombres.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNombresKeyTyped(evt);
            }
        });
        jPanel1.add(textoNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 230, -1));

        textoApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoApellidosKeyTyped(evt);
            }
        });
        jPanel1.add(textoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 230, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Builder 64x64.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        BotonBuscar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        BotonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BotonRegistrar.setText("Registrar");
        BotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        BotonActualizar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BotonActualizar.setText("Actualizar");
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        BotonEliminar1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BotonEliminar1.setText("Inhabilitar");
        BotonEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminar1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Apellidos:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Estado Civil:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        groupEstadocivil.add(radioCasado);
        radioCasado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioCasado.setText("Casado");
        jPanel1.add(radioCasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        groupGenero.add(radioFemenino);
        radioFemenino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioFemenino.setText("Femenino");
        jPanel1.add(radioFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        groupEstadocivil.add(radioSoltero);
        radioSoltero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioSoltero.setText("Soltero");
        jPanel1.add(radioSoltero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        groupGenero.add(radioMasculino);
        radioMasculino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioMasculino.setText("Masculino");
        jPanel1.add(radioMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Genero:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        groupGenero.add(radioMasculino1);
        radioMasculino1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioMasculino1.setText("Masculino");
        jPanel1.add(radioMasculino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        groupGenero.add(radioFemenino1);
        radioFemenino1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioFemenino1.setText("Femenino");
        jPanel1.add(radioFemenino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Genero:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        botonCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cargos 48x48.png"))); // NOI18N
        botonCargos.setBorder(null);
        botonCargos.setBorderPainted(false);
        botonCargos.setContentAreaFilled(false);
        botonCargos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargosActionPerformed(evt);
            }
        });
        jPanel1.add(botonCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 50, 60));

        ComboBoxCargos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(ComboBoxCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 190, 40));

        BotonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Update 32x32.png"))); // NOI18N
        BotonUpdate.setBorder(null);
        BotonUpdate.setBorderPainted(false);
        BotonUpdate.setContentAreaFilled(false);
        BotonUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(BotonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarActionPerformed
        if((textoIdentificacion.getText().length()==0)||
           (textoNombres.getText().length()==0)||
           (textoApellidos.getText().length()==0)||
           (textoTelefono.getText().length()==0)){
           JOptionPane.showMessageDialog(null,"Llenar todos los campos");
           }else{

            String estadocivil = null;
            if (radioSoltero.isSelected()){
                estadocivil = "Soltero";           
            }else if(radioCasado.isSelected()){
                estadocivil = "Casado";
            }else {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un estado civil");
            }
            
            String genero = null;
            if (radioMasculino.isSelected()){
                genero = "Masculino";           
            }else if(radioFemenino.isSelected()){
                genero = "Femenino";
            }else {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un genero");
            }

            Cargos c = (Cargos)ComboBoxCargos.getSelectedItem();
  
            empleado.setIdentificacion(textoIdentificacion.getText());
            empleado.setNombres(textoNombres.getText());
            empleado.setApellidos(textoApellidos.getText());
            empleado.setEstadoCivil(estadocivil);
            empleado.setGenero(genero);
            empleado.setTelefono(textoTelefono.getText());
            empleado.setCargo(c);
            empleado.setEstado("On");
            try {
                    ejc.create(empleado);
                    mensaje = "Empleado registrado";
                    JOptionPane.showMessageDialog(null, "Empleado registrado");
                } catch (Exception e) {
                    System.out.println("Mensaje en guardar: " + e.getMessage());
                    mensaje = "No se pudo registrar el empleado. \n" + e.getMessage();  
                    JOptionPane.showMessageDialog(null, "No se pudo registrar el empleado. \n" + e.getMessage());
                }
        }
           limpiarCampos();
    }//GEN-LAST:event_BotonRegistrarActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        if((textoIdentificacion.getText().length()==0)||
           (textoNombres.getText().length()==0)||
           (textoApellidos.getText().length()==0)||
           (textoTelefono.getText().length()==0)){
           JOptionPane.showMessageDialog(null,"Llenar todos los campos");
           }else{

        String estadocivil;
            if (radioSoltero.isSelected()){
                estadocivil = "Soltero";           
            }else
                estadocivil = "Casado";
            
        String genero;
            if (radioMasculino.isSelected()){
                genero = "Masculino";           
            }else
                genero = "Femenino";

        Cargos c = (Cargos)ComboBoxCargos.getSelectedItem();

            empleado.setIdentificacion(textoIdentificacion.getText());
            empleado.setNombres(textoNombres.getText());
            empleado.setApellidos(textoApellidos.getText());
            empleado.setEstadoCivil(estadocivil);
            empleado.setGenero(genero);
            empleado.setTelefono(textoTelefono.getText());
            empleado.setCargo(c);
            empleado.setEstado("On");
            try {
                    ejc.edit(empleado);
                    mensaje = "Empleado actualizado";
                    JOptionPane.showMessageDialog(null, "Empleado actualizado");
                } catch (Exception e) {
                    System.out.println("Mensaje en guardar: " + e.getMessage());
                    mensaje = "No se pudo actualizar el empleado. \n" + e.getMessage();  
                    JOptionPane.showMessageDialog(null, "No se pudo actualizar el empleado. \n" + e.getMessage());
                }
        
        limpiarCampos();

        }
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void BotonEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminar1ActionPerformed

        if((textoIdentificacion.getText().length()==0)||
           (textoNombres.getText().length()==0)||
           (textoApellidos.getText().length()==0)|| 
           (textoTelefono.getText().length()==0)){
            JOptionPane.showMessageDialog(null,"Busque el empleado que desea inhabilitar");
        }else{
            inhabilitarEmpleado(textoIdentificacion.getText());
            JOptionPane.showMessageDialog(null, "Empleado inhabilitado");
            
            limpiarCampos();
        }  



    }//GEN-LAST:event_BotonEliminar1ActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        String identificacion = textoIdentificacion.getText();
        if((textoIdentificacion.getText().length()==0)){
           JOptionPane.showMessageDialog(null,"Ingrese el n° de identificación");
        }else{
        identificacion = textoIdentificacion.getText();
        Empleados c = ejc.findEmpleados(identificacion);
        if (c == null){

            limpiarCampos();

        }else
        {    
          if(c.getEstado().equals("Off")){
            JOptionPane.showMessageDialog(null,"Este empleado ha sido inhabilitado");
            
            limpiarCampos();
          }
        else  
        { 
          textoNombres.setText(c.getNombres());
          textoApellidos.setText(c.getApellidos());
          
            String estado = c.getEstadoCivil();
            if(estado.equals("Casado")){
               radioCasado.setSelected(true); 
            }else{
                radioSoltero.setSelected(true);
            }
            
            String genero = c.getGenero();
            if(genero.equals("Masculino")){
               radioMasculino.setSelected(true);
            }else{
                radioFemenino.setSelected(true);
            }
            
          textoTelefono.setText(c.getTelefono());  

            ComboBoxCargos.setSelectedItem(c.getCargo());
        }
        }}
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void textoIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoIdentificacionKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo ingresar números");
        }
        int caracteres=10;
        if(textoIdentificacion.getText().length()>=caracteres){
            JOptionPane.showMessageDialog(null, "Sobrepasa la cantidad de números permitidos");
        }                 
    }//GEN-LAST:event_textoIdentificacionKeyTyped

    private void textoTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoTelefonoKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo ingresar números");
        }
        int caracteres=10;
        if(textoTelefono.getText().length()>=caracteres){
            JOptionPane.showMessageDialog(null, "Sobrepasa la cantidad de números permitidos");
        }  
    }//GEN-LAST:event_textoTelefonoKeyTyped
  //||(c == KeyEvent.VK_DELETE)
    private void textoNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNombresKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z')&&(c < 'A' || c > 'Z')&&(c != 'ñ')&&(c != 'Ñ')){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo ingresar letras");
        }
    }//GEN-LAST:event_textoNombresKeyTyped

    //(c != KeyEvent.VK_SPACE)
    private void textoApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoApellidosKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z')&&(c < 'A' || c > 'Z')&&(c != 'ñ')&&(c != 'Ñ')){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo ingresar letras");
        }
    }//GEN-LAST:event_textoApellidosKeyTyped

    //PARA BUSCAR INGRESANDO LA IDENTIFICACION Y OPRIMIENDO LA TECLA ENTER:
    private void textoIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoIdentificacionActionPerformed
        String identificacion = textoIdentificacion.getText();
        if((textoIdentificacion.getText().length()==0)){
           JOptionPane.showMessageDialog(null,"Ingrese el n° de identificación");
        }else{
        identificacion = textoIdentificacion.getText();
        Empleados c = ejc.findEmpleados(identificacion);
        if (c == null){

            limpiarCampos();
            
        }else
        { textoNombres.setText(c.getNombres());
          textoApellidos.setText(c.getApellidos());
          
          String estado = c.getEstadoCivil();
            if(estado.equals("Casado")){
               radioCasado.setSelected(true); 
            }else{
                radioSoltero.setSelected(true);
            }
            
            String genero = c.getGenero();
            if(genero.equals("Masculino")){
               radioMasculino.setSelected(true);
            }else{
                radioFemenino.setSelected(true);
            }
          
          textoTelefono.setText(c.getTelefono());  }
        }
    }//GEN-LAST:event_textoIdentificacionActionPerformed

    private void botonCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargosActionPerformed
        if(c == null){
            c = new CargosGUI();
            c.setVisible(true);

        }else
        c.setVisible(true);
        c.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonCargosActionPerformed

    private void BotonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUpdateActionPerformed
        ComboBoxCargos.removeAllItems();
        llenarComboBoxCargos(ComboBoxCargos);
    }//GEN-LAST:event_BotonUpdateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonEliminar1;
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JButton BotonUpdate;
    private javax.swing.JComboBox<Cargos> ComboBoxCargos;
    private javax.swing.JButton botonCargos;
    private javax.swing.ButtonGroup groupEstadocivil;
    private javax.swing.ButtonGroup groupGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioCasado;
    private javax.swing.JRadioButton radioFemenino;
    private javax.swing.JRadioButton radioFemenino1;
    private javax.swing.JRadioButton radioMasculino;
    private javax.swing.JRadioButton radioMasculino1;
    private javax.swing.JRadioButton radioSoltero;
    private javax.swing.JTextField textoApellidos;
    private javax.swing.JTextField textoIdentificacion;
    private javax.swing.JTextField textoNombres;
    private javax.swing.JTextField textoTelefono;
    // End of variables declaration//GEN-END:variables


}
